### PR TITLE
feat: add store as a target

### LINKED ISSUE #7: Add store as a target
Add store (storeWritable) as a target to rxSample

### PR DESCRIPTION
**Pull request by AndreyTheWeb**
- Add StoreWritable as a target to rx-sample
-  Update smartbundle to latest

### CODE REVIEW

**Comment by AndreyTheWeb** [comment]
close https://github.com/Voiso/rx-sample/issues/7

**Comment by no-treasure** [comment]
LGTM

**Review by no-treasure — APPROVED** [review]

**Comment by no-treasure** [comment]
1 issue:
Seems like here is no strict type connection between source and target, in this example:
```ts
    const mockChannel = new Subject<string>();
    const subscribe = createEvent();
    const unsubscribe = createEvent();
    const $processedMessage = createStore<string>("");

    rxSample({
      source: mockChannel,
      subscribeOn: subscribe,
      unsubscribeOn: unsubscribe,
      target: $processedMessage,
    });

```
if i changed 
```ts
    const mockChannel = new Subject<string>();
```
to
```ts
    const mockChannel = new Subject<Array<string>>();
```
Should be type error from rxSample "target should be the same type as source"

**Comment by AndreyTheWeb** [comment]
@no-treasure yes, from the outside it looks like a bug (as feature), but I want to keep the ability to pass event to target of any type (for example in case we want to just get a signal), but as soon as user uses fn, typing will penalize him for wrong type in target

**Comment by AndreyTheWeb** [comment]
@no-treasure i change types, for more strict usage. Now you must same types for source and target, and if you want different type in target, please use fn

**Pull request merged**
